### ISSUE TITLE
Extract Dir fuction crashes on Windows machines due to illegal characters in path

### ISSUE THREAD

**Issue by markshur** [krypto5863/COM3D2-Arc-Outfits-Extractor#4]
Application crashes when extracting GameData files in COM3D2 in Windows.  You need to filter out illegal characters such as ':' before creating subdirectories.

![image](https://github.com/krypto5863/COM3D2-Arc-Outfits-Extractor/assets/6880292/5f973cde-1f03-4d89-b1e2-bf4039b9d091)

**Comment by krypto5863** [comment]
fixed as of the 2.0 rewrite.
